Dev.named tuple
WordWeaverTools/wordweaver pull request #34
Opened 2023-07-04 17:28 UTC by dlothian

Compatible with the new data format for the "output" attribute of a conjugation ResponseObject.

2023-07-04 18:35 UTC, roedoejet requested changes
Just looks like the `projects/word-weaver/src/app/core/conjugation/conjugation.service.ts` file maybe got accidentally committed. After removing that it all looks good to me, thanks @dlothian !

2023-07-04 18:35 UTC, roedoejet commented on projects/word-weaver/src/app/core/conjugation/conjugation.service.ts
> +import { type } from "os";
This import is errant - please remove.

2023-07-04 18:35 UTC, roedoejet commented on projects/word-weaver/src/app/core/conjugation/conjugation.service.ts
> +        console.log(x, selection[x]);
We don't need console.logs in here in production

2023-07-05 17:40 UTC, joanise commented
These changes need to be made in parallel in `config.fr.ts` and wordweaver's backend `fr.model.py`. Working on that now.

2023-07-05 19:58 UTC, joanise approved these changes
This is ready to merge now.

2023-07-05 20:14 UTC, roedoejet approved these changes
great thanks all!

2023-07-05 20:20 UTC, merged